### ISSUE TITLE
Scraper broken

### ISSUE THREAD

**Issue by phearcest** [aj0strow/espn-scraper#5]
The scraper does not seem to be getting scores correctly for ncf or nfl. The unit tests are failing.

**Comment by koryteg** [comment]
plus one this

**Comment by aj0strow** [comment]
@ryan-mcandrews @koryteg ok so fix it :)

**Comment by koryteg** [comment]
after looking into this further. this is a bigger rewrite than initially thought. 
espn has completely redone the scores pages.
issue 1: 
all the content is now generated by javascript, so the `HTTParty` call is not returning all the html needed, the response needs to wait for javascript to render all the html in order to parse it.
issue 2:
all the html is reformatted. this isn't as big of a deal just need to change the css selectors to properly get the data. from what I can tell there is still a really consistent convention to follow.

I'll look into solutions for the JS (ie phantom or selinium) but if you have know a direction to go let me know.

**Comment by aj0strow** [comment]
@koryteg it seems the data is available now in json in a script

https://github.com/aj0strow/espn-scraper/pull/6

**Comment by aj0strow** [comment]
It might be worth checking out https://github.com/tenderlove/rkelly to make it more robust.
